### ISSUE TITLE
Knitting errors

### ISSUE THREAD

**Issue by jvcasillas** [kparrish92/ds4ling_final#2]
The manuscript Rmd is extremely slow and gives the following error. 

<img width="870" alt="Screen Shot 2021-05-12 at 13 24 30" src="https://user-images.githubusercontent.com/1747068/118018171-756a6180-b325-11eb-97db-33e1c3b48a64.png">

I think you meant to set `eval=T` to false. Also, all the chunks have the same name (that will give an error too. 

The slides are also extremely slow to knit. Fail with the following error: 

<img width="852" alt="Screen Shot 2021-05-12 at 13 30 32" src="https://user-images.githubusercontent.com/1747068/118018806-43a5ca80-b326-11eb-8564-81ad5fa8fc22.png">

**Comment by kparrish92** [comment]
@jvcasillas it looks I like I made a mistake and somehow had old versions of the manuscript and slides on this repo. I fixed this and everything knits now (and much much faster)
